# =============================================
# SERVER
# =============================================
server.port=8080

# =============================================
# MYSQL - Base de Datos Relacional
# =============================================
spring.datasource.url=jdbc:mysql://localhost:3306/sportlife_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# =============================================
# MONGODB - Base de Datos No Relacional
# =============================================
spring.data.mongodb.uri=mongodb://localhost:27017/sportlife_logs
spring.data.mongodb.database=sportlife_logs

# =============================================
# JWT
# =============================================
jwt.secret=sportlife_secret_key_dosw_2024_super_secure
jwt.expiration=86400000

# =============================================
# SWAGGER
# =============================================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# =============================================
# APP INFO
# =============================================
spring.application.name=ECI-SportLife
